### ISSUE TITLE
callback.php not secure

### ISSUE THREAD

**Issue by danmarsden** [Snickser/moodle-paygw_cryptocloud#18]
your callback.php "trusts" the raw data sent by the end user - it does not make a check to cryptocloud "has this payment been received.

please also review: https://moodledev.io/general/development/policies/security#dont-trust-any-input-from-users

note - this is a clear blocker for plugins db approval. Payment plugins must check with the provider if a payment has been recieved - not just allow the end user to post to the script a "Success" call.

**Comment by Snickser** [comment]
Fixed.
Added secret token verification code.

**Comment by Snickser** [comment]
use required_param()
