### ISSUE TITLE
please dont call curl_init directly

### ISSUE THREAD

**Issue by danmarsden** [Snickser/moodle-paygw_cryptocloud#19]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

This isn't documented well but search core code for "curl" to see examples of it's use.

**Comment by Snickser** [comment]
I couldn’t get curl() to do authorization for my other plugin, so I used a direct call.

**Comment by Snickser** [comment]
Done.
