### ISSUE TITLE
This data needs to be clean before using

### ISSUE THREAD

**Issue by purnendudash** [Snickser/moodle-paygw_cryptocloud#27]
https://github.com/Snickser/moodle-paygw_cryptocloud/blob/0016077ae558a1d04ea92cb5866a894be61b4a73/method.php#L41

**Comment by Snickser** [comment]
Done.

**Comment by Snickser** [comment]
Clean from what?
That code is converted from unicode, like this
"\u0414\u043e\u0441\u0442\u0443\u043f \u043a \u0442\u043e\u043f\u0438\u043a 3"
to utf8.

**Comment by Snickser** [comment]
Like this?
`$description = json_decode('"'.$description.'"');`
