### ISSUE TITLE
Sesskey needs to be implemented

### ISSUE THREAD

**Issue by purnendudash** [Snickser/moodle-paygw_cryptocloud#28]
As its was being called from js file directly. the sesskey should be implemented and needs to be checked before processing the data.

https://github.com/Snickser/moodle-paygw_cryptocloud/blob/0016077ae558a1d04ea92cb5866a894be61b4a73/method.php#L43

**Comment by Snickser** [comment]
How transfer sesskey from JS to PHP ?

**Comment by purnendudash** [comment]
https://moodledev.io/general/development/policies/security
https://moodledev.io/general/development/policies/security/crosssite-request-forgery


These doc will give you the idea

**Comment by Snickser** [comment]
I downloaded many approved payment modules, for example, and none of them used sesskey :(
