### ISSUE TITLE
Incorrect URL in forms 

### ISSUE THREAD

**Issue by volodymyrdovhan** [Snickser/moodle-paygw_cryptocloud#45]
Hello,
I have installed Moodle in '/moodle' subdirectory and when I try to pay or submit the password - system redirects me to the wrong URL.

![image](https://github.com/user-attachments/assets/8bcd84ba-ab0f-4681-a2b4-a5da9c765a7e)
![image](https://github.com/user-attachments/assets/fd6b437f-f33c-4581-bca7-d139f21097e8)
![image](https://github.com/user-attachments/assets/5a39479e-116a-4e14-8d11-020feadeac3b)

**Comment by Snickser** [comment]
As far as i know moodle can't work on non-standard ports.

**Comment by Snickser** [comment]
The fix is ​​available in the dev branch, I'll add it to the main branch later.
