### ISSUE TITLE
Plain hardcoded text with donation information

### ISSUE THREAD

**Issue by volodymyrdovhan** [Snickser/moodle-paygw_cryptocloud#49]
Hello,
I found plain hardcoded text in the plugin:

![image](https://github.com/user-attachments/assets/cae7f3ec-b576-4dba-ada2-c99313ab5e5d)
![image](https://github.com/user-attachments/assets/4407e7d2-dd1e-48e1-9be6-a0746ca09e47)

Theoretically, it should be defined in the language file and translated, but I understand why it is hardcoded - to avoid removal from the page. We will need to discuss this in the tracker.

**Comment by Snickser** [comment]
I can move it to the language file, it doesn't matter to me.

**Comment by volodymyrdovhan** [comment]
Yes, that will be great. Please move it to the language file.
